### ISSUE TITLE
Missing doc

### ISSUE THREAD

**Issue by liannario** [CloudTestDrive/EventLabs#12]
Within https://github.com/CloudTestDrive/EventLabs/blob/master/BlockChain/readme.md, https://github.com/CloudTestDrive/EventLabs/blob/master/BlockChain/Lab1_BCS_Network_HOL.docx this document is missing (returns 404)

**Comment by janleemans** [comment]
Thanks for pointing this out, the latest version of that lab file got a new name.  Should work now.
